title: Rodolfo Maranhao
logo: "images/DS - Rodolfo Antunes Maranhao.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my Portfolio! As a recent graduate from a data science bootcamp, 
  I bring a unique perspective and a diverse set of skills to the world of data.  
  I am passionate about extracting actionable insights from complex data to drive meaningful outcomes. 
  Feel free to explore my portfolio and contact me on Linkedin as we explore the future of data together.
  <br><br>
  <a href="https://www.linkedin.com/in/rodolfo-antunes-maranhão">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
