title: Rodolfo Maranhao
logo: "images/DS - Rodolfo Antunes Maranhao.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my Portfolio! As a recent data science bootcamp graduate, I offer a unique perspective and a diverse skill set in the field of data. 
  I am passionate about extracting actionable insights from complex data to achieve meaningful outcomes. 
  <br><br>
  <a href="https://www.linkedin.com/in/rodolfo-antunes-maranhão">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
